config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get "pages/:permalink" => "pages#permalink", as: "permalink" # using it in ruby: permalink_path
  root to: 'home#index'
  resources :games, only: %i[index show]
  resources :publishers, only: %i[index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :publisher
  validates :title, :year, :rank, :genre, :sales, presence: true
  validates :year, :rank, numericality: { only_integer: true }
  validates :sales, numericality: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/production.rb
class Production < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :games
  validates :name, presence: true, uniqueness: true

  def self.ordered_by_games
    self.select('publishers.*')
        .select('COUNT(publishers.id) as game_count')
        .left_joins(:games)
        .group('publishers.id')
        .order('game_count DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.includes(:publisher).all.order('sales DESC')
  end

  def show
    @games = Game.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @games = Game.includes(:publisher)
                 .order('sales DESC')
                 .limit(10)

    @publishers = Publisher.ordered_by_games.limit(10).limit(10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[show edit update destroy]
  http_basic_authentication_with name: 'admin', password: 'secret', except: [:show]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publishers = Publisher.order_by_games
  end

  def show
    @publisher = Publisher.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/production_companies_helper.rb
module ProductionCompaniesHelper
end

app/views/common/_footer.html.erb
<hr>
<footer>
  <p><em>Copywrong IMDB 2021</em></p>
  <ul class="mt-5">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Top 100 games", games_path %></li>
    <li><%= link_to "Top Production Companies", publishers_path %></li>
    <li><%= link_to 'About The Data', permalink_path('about_the_data')%></li>
    <li><%= link_to 'Contact Us', permalink_path('contact')%></li>
  </ul>
</footer>

app/views/games/_games.html.erb
<h2 class="title is-2">
<% if show_link %>
  <%= link_to game.title, game %>
<% else %>
  <%= game.title %>
<% end %>
</h2>


<article class="message is-dark">
  <div class="message-header">
    <p>Description</p>
  </div>
  <div class = "message-body">
    <%= game.genre %>
  </div>
</article>

<progress class="progress is-info" value="<%= game.sales %>" max=10>
  <%= game.sales%>
</progress>

<p>
  <strong>Global Sales: </strong>
  <%= game.sales%>
</p>

<p>
  <strong>Release Year: </strong>
  <%= game.year %>
</p>

<p>
<strong>Genre: </strong>
<%= game.genre %>
</p>

<p>
  <strong>Publisher: </strong>
  <%= link_to game.publisher.name, game.publisher%>
</p>

<hr>

app/views/games/index.html.erb
<h2 class="title is-2">Top 100 Games</h2>

<%= render partial: 'game', object: @games, locals: {show_link: true }%>

app/views/games/show.html.erb
<% content_for(:html_title) { @game.title}%>


<%= render partial: 'game', object: @game, locals: {show_link: false }%>

app/views/home/index.html.erb
<div class="columns">
  <div class="column">
    <h2 class="title is-2">Top 10 games</h2>
    <ol class="ml-5">
    <% @games.each do |game| %>
      <li>
        <%= link_to game.title, game%>
        <em>(<%= game.publisher.name%>)</em>
      </li>
    <%end%>
    </ol>
  </div>
  <div class="column">
    <h2 class="title is-2">Top 10 Publishing Companies</h2>
    <ol class="ml-5">
    <%= render @publishers %>
    </ol>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + " - " if content_for?(:html_title)%>Top 100 games</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cnd.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <section class= "section">
      <div class="container">
      <h1 class="title is-1"><%= link_to 'Top Games by global sales', root_path %></h1>
      </div>
      <%= yield %>

      <% if controller_name == 'home'%>
        <p>This is the home page </p>
      <%else%>
        <%= render partial: 'common/footer'%>
      <%end%>
    </section>

  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/production_companies/_production_company.html.erb
<li>
  <%= link_to publisher.name, publisher%>
  <em>(<%= pluralize publisher.game_count, "Top Game" %>)</em>
</li>

app/views/publishers/_publisher.html.erb
<li>
  <%= link_to publisher.name, publisher%>
  <em>(<%= pluralize publisher.game_count, "Top Game" %>)</em>
</li>

app/views/publishers/index.html.erb
    <h2 class="title is-2">Top Publishing Companies</h2>
    <ol class="ml-5">
    <% @publishers.each do |publisher| %>
      <li>
        <%= link_to publisher.name, publisher%>
        <em>(<%= pluralize publisher.game_count, "Top game"%>)</em>
      </li>
    <%end%>
    </ol>

app/views/publishers/show.html.erb
<h2 class="title is-2"><%= @publisher.name %></h2>

<p class='mb-5'>
This publishing company made <%= @publisher.games.count %> of the top 100 games.
</p>

<h3 class='title is-3'>Games Made By <%= @publisher.name %></h3>
<ul>
  <%= render partial: @publisher.games, locals: {show_link:true} %>
</ul>